### ISSUE TITLE
MetaMask logo for Twitter Support

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#100]
from Dan

"I think for anti-phishing it’s actually kinda important. @christian.jeria do you think you could throw a medic hat on a fox for the support twitter account?"

![image](https://user-images.githubusercontent.com/597770/59291719-b7219780-8c38-11e9-9a98-1837f0bdbd3f.png)

**Comment by bdresser** [comment]
don't we already have a version with a hard hat somewhere!

**Comment by cjeria** [comment]
@bdresser not sure! I think @danfinlay created that one before I started?

How about this option?
![metamask-support-fox](https://user-images.githubusercontent.com/597770/59299066-0e2f6880-8c49-11e9-88aa-6eaabcd4b7ef.png)

**Comment by cjeria** [comment]
I really like github's support imagery
![image](https://user-images.githubusercontent.com/597770/59364121-936f5780-8cf3-11e9-8013-11fb9ab7eff3.png)

So I made a version inspired by it
![image](https://user-images.githubusercontent.com/597770/59364019-6ae75d80-8cf3-11e9-9d68-eff831d595fe.png)

**Comment by cjeria** [comment]
All four options side by side
![image](https://user-images.githubusercontent.com/597770/59370456-c3245c80-8cff-11e9-8f69-761c0df0db2c.png)

**Comment by cjeria** [comment]
Finalist per convos on support slack channel added support label for added 

Downloadable asset:
![Twitter Support logo](https://user-images.githubusercontent.com/597770/59624084-18db7900-90f3-11e9-8b99-b098b5be3593.png)

Mockup of what it will look like:
![image](https://user-images.githubusercontent.com/597770/59624834-111cd400-90f5-11e9-8f95-8e24e3b47956.png)

**Comment by dpazdan** [comment]
Looks great! 👍 🦊❤️
