### ISSUE TITLE
Draft MetaMask Support Logo

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#101]
We have [a support account](https://twitter.com/metamasksupport) that our support team replies from, but it deserves at least some slightly differentiated branding.

David did his best, but I'm not sure it's reflecting the brand optimally:
<img width="365" alt="Screen Shot 2019-06-11 at 10 08 22 AM" src="https://user-images.githubusercontent.com/542863/59292010-f350fa00-8c30-11e9-95f3-fee64b948498.png">

**Comment by danfinlay** [comment]
I was thinking a quick little "medic" hat would be nice. I swear I made one of these at some point.

**Comment by danfinlay** [comment]
I think this might do:

<img width="878" alt="medic-fox" src="https://user-images.githubusercontent.com/542863/59292262-91dd5b00-8c31-11e9-988d-063829398c5d.png">

Used this hat:
![kisspng-nurses-cap-nursing-hat-clip-art-medical-hat-cliparts-5a89da17b339c6 6329848315189837037341](https://user-images.githubusercontent.com/542863/59292283-99046900-8c31-11e9-98d9-b3e3b2bc1ed9.png)

**Comment by cjeria** [comment]
This relates to #100

**Comment by cjeria** [comment]
closing in favor of #100
