### ISSUE TITLE
Error screen for offline behavior

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#102]
See https://github.com/MetaMask/MetaMask/issues/293

**Comment by cjeria** [comment]
Found a nice resource for 404 error page illustrations we could repurpose for offline message here: https://www.kapwing.com/404-illustrations

I mocked this up. Thoughts?
![image](https://user-images.githubusercontent.com/597770/59621003-81bef300-90eb-11e9-9924-6aa33dc91834.png)

**Comment by omnat** [comment]
Nice! A suggestion to make 'try again' clickable, so after user checks internet connection, they could either pull down to reload (not everyone might know of this pattern to pull down), or tap 'try again' to reload

**Comment by cjeria** [comment]
Final screen and link to the prototype: 
https://www.figma.com/proto/ZjvqFYvSwB90oC81N0PMHjE1/Mobile-Browser?node-id=249%3A0&viewport=-18%2C435%2C1.0609722137451172&scaling=scale-down

![image](https://user-images.githubusercontent.com/597770/60140230-3e5d2800-976e-11e9-93f6-65d51b3d52e3.png)

**Comment by bdresser** [comment]
how do I close this, or navigate away? do we still have the top-bar nav or anything like that? if I have no internet and my only option is "Try Again" I think I will be stuck in a loop

**Comment by brunobar79** [comment]
@bdresser  I've added a close icon on the navbar to handle that.

**Comment by cjeria** [comment]
oh sorry, i forgot to keep the browser navbar elements in my mockup here! was thinking this would only happen in the browser. Are there are other situations that the app will show this outside of the browser?

**Comment by brunobar79** [comment]
@cjeria  never mind, It's not a critical screen. I kept your design and added an X at the top corner.
