### ISSUE TITLE
InstaPay "receive" option

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#123]
We should have a recieve flow for InstaPay to help users through the process of requsting or sharing their address

**Comment by omnat** [comment]
Sprint 18 goal: 
- Prototype + discussion
- If tried & tested pattern used, dev-handoff

**Comment by bdresser** [comment]
per @brunobar79 in connext v2 the instapay wallet address is going to be different than the user's main ethereum address

**Comment by cjeria** [comment]
In mobile design sync, we decided to go with "option 2" as the solution to the "receive" option. (see below). 

Some considerations
- **Receive** today would show the accounts public address, however in the near future, the account address for instapay will be a totally new custom address derived from the wallet's seed phrase.
- The above infrastructural change means that we'll need to design instapay to have feature parity as a normal eth account with QR scanner (to scan recipient addresses) and request payment feature to name a couple.
- Information architecture consideration: We'll need to consider where in the wallet this new type of account will be accessed ei, will it be considered another type of account accessible through the main account list or should it be accessed within all account (like it is currently implemented)?

Here's a link to the [figma prototype](https://www.figma.com/proto/h5FawCpd949EjiXzLU1j8h/Mobile-Onboarding-Carousel?node-id=81%3A206&viewport=540%2C-643%2C0.3130502998828888&scaling=min-zoom)
![image](https://user-images.githubusercontent.com/597770/63038150-8ce59380-be8e-11e9-9e5c-5d867d8f6a8c.png)

**Comment by omnat** [comment]
Ready for dev-handoff
