### ISSUE TITLE
Preventing common errors, and guiding users to help recover from incomplete actions

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#138]
Details of problems identified and possible actions here: https://docs.google.com/document/d/1fxPRPePfcDJ-5Db9lxccpu0AqsAXEp9fcBSWH90SKp4/edit
Related to Blocknative suggestions in their audit as well.

1. Alert users when they are trying to submit a duplicate txs
2. Notify users pro-actively when  for transactions are dropped / unapproved / pending for long. To notify users that the tx they wanted to send couldn’t be sent, so try again with higher tx fee / speedup . or cancel, etc.
3. Guide users to get funds when insufficient funds error (talked about this to @rachel.cope just today)

**Comment by omnat** [comment]
- Blocknative, Rimble have done some pre-work on this. Check out their work to begin with
- These might overlap with #139

**Comment by bdresser** [comment]
@bdresser to come up with 
(a) categories of error
(b) a list of flows where these errors could be useful

**Comment by omnat** [comment]
Sprint 21: Discuss this one at the retreat

**Comment by omnat** [comment]
Sprint Sept 30 @bdresser I totally forgot to talk about this at retreat. Where's this at? Should we plan it for this week, or keep for post devcon sprint? 
We aren't planning this for now, maybe this makes to sprint work at the end of week design sync (thursday)

**Comment by bdresser** [comment]
happy to have a chat about it later this week but realistically we probably won't get to it until after devcon, right?

**Comment by omnat** [comment]
(from design sync) Background reading / reference to past chats here:
https://github.com/MetaMask/metamask-mobile/issues/341

**Comment by bdresser** [comment]
#### Summary
This project is about creating two re-usable components 
* One screen for "error prevention" that we can use throughout the app as a "warning" screen. 
* One screen for "error recovery" that we can use throughout the app as an "oops, something went wrong!" screen

Each case will probably have a different "suggested action" and will certainly have different copy, so leaving some flexibility in the CTA buttons & copy space is a good idea. (I've added some examples of what those CTAs could be.

#### Other considerations
* do we want to allow for a "don't show this message again" checkbox ?
* are there other flows / common hiccups that we should include in these lists
* is one screen sufficient for each, or is there a gentler or more explanatory flow that we should use to help mitigate errors like these?
* this will ship to extension first, but could easily add to mobile shortly
* some backstory & first principles from @omnat here: https://github.com/MetaMask/Design/issues/125

#### Error prevention 
* Retrying duplicate transaction (https://github.com/MetaMask/metamask-extension/issues/4185)
  * Primary button `speed up or cancel existing tx` Secondary `Proceed anyway` 
* User is submitting transaction, but several are already pending (https://github.com/MetaMask/metamask-extension/issues/5126)
  * Could prompt user to speed up or cancel
  * Primary button `speed up or cancel existing tx` Secondary `Proceed anyway` 
* Submitting a tx with gas unnecessarily high
  * Primary button `Adjust gas` Secondary `Proceed anyway`
* Submitting a tx to a token/contract address
  * * Primary button `Edit recipient` Secondary `Proceed anyway`

#### Error recovery 
* Transaction has been pending for a long time (https://github.com/MetaMask/metamask-extension/issues/5738)
  * Should prompt user to speed up or cancel
  * Could also be making these buttons more apparent passively
* Transaction failed on-chain
* User tries to Send but has no ETH

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/5211

**Comment by omnat** [comment]
@rachelcope to add links to the latest here.
Next steps in Sprint 23: 
- go through the rest of the use-cases, 
- revisit copy for errors
- address questions from design sync

**Comment by omnat** [comment]
Dev hand-off planned for Nov 13
