### ISSUE TITLE
Update transaction history

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#139]
Part of this work https://docs.google.com/document/d/1E0GaCm8zIX0nkOAYWoMcIHULh74XS0gLIxEqiKDA7Qc/edit?ts=5d4206b4

Specific applications for
- Improving transaction history: WIP brief https://docs.google.com/document/d/1KcdMu5CGRtJjA5GfkjEkTD-DUTLC6TctbB71qkypGaE/edit#
- Clearer copy for browser notifications, which is also consistent with tx history - ‘Sending ETH’ , ‘Cancelling transaction’, ‘Bid transaction confirmation’ instead of ‘Transaction 104 submitted’

**Comment by rachelcope** [comment]
Figma Design for proposed transaction history: https://www.figma.com/file/xyDiUxhOnIL8bnewF7jhnz/Transaction-Content?node-id=0%3A1

Content / Use cases: https://docs.google.com/spreadsheets/d/19c3q1bz5Wz2iMd-ITpOjJTXNkJeu14ZoS_H1aV-timM/edit#gid=1528400304

**Comment by omnat** [comment]
Next steps (sprint of 30 Sept):

- [ ] Add new icons for tx history in design system
- [ ] Get answers to some open questions 
- [ ] Interaction design exploration for progressive reveal of txs
- [ ] Schedule a hand-off meeting

**Comment by omnat** [comment]
Dev hand-off planned for Nov 13
