### ISSUE TITLE
Design QA (Sprint 19)

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#140]
- [x] Contact list in Settings: usability bugs
 - [x] TX history UI bug -- The layout is off. Extra white space between tx title and nonce/date under, looks pushed down, breaking the layout.

**Comment by cjeria** [comment]
Created a new issues for each fixL
- Contact list updates [here](https://github.com/MetaMask/metamask-extension/issues/7069)
- TX history UI bug issue [here ](https://github.com/MetaMask/metamask-extension/issues/7036)
