### ISSUE TITLE
Ether-less Confirm TX Screens (Pure Function Calls)

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#16]
Dan commented:

>Pure Function Calls

>Not all transactions have ether implicitly attached to them. Often, the transaction really is about the Data. For those, the big header (about 30% of the view) would be dedicated to showing $0.00 0.0000 ether.

>For cases when there is no ether being sent, and there is data associated with the transaction, and we are able to retrieve a function name from the on-chain registry, I strongly feel we should show the function name as a primary label on the confirmation screen. It is clearly the most useful information we could show the user.

**Comment by cjeria** [comment]
Possibly detect pure function calls (etherless actions) and swap out the body components with something that makes more sense with this specific type of function call. 
![confirm screen - method copy](https://user-images.githubusercontent.com/597770/40396473-1cd53234-5de2-11e8-9369-79efd0f31fa7.png)

**Comment by bdresser** [comment]
as discussed today, this can probably follow the designs in #11 closely, just need to replace the $/ETH value with a text treatment of the function call or something along those lines

user will still need to pay gas & would probably like the additional stuff in the `data` tab.

**Comment by bdresser** [comment]
this will be handled as part of #80
