### ISSUE TITLE
Plugin use-cases (that people made already)

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#161]
UX perspective on --- to re-imagine to-be impact on dapp experiences

- contract account continued 
- spend limit + override pop-up
- plasma
- ethwaterloo: Built at ETHWaterloo 2019 Hackathon 
https://devpost.com/software/dc-wallet  
https://devpost.com/software/carbonguilt 
https://devpost.com/software/connexion-vy3a9c Decentralized notification system https://devpost.com/software/wallet-notify 
 Conversation in Slack: https://consensys.slack.com/archives/G1L7H42BT/p1571975710151900  
Decentralized notification system  https://mailchain.xyz/index.html

**Comment by danfinlay** [comment]
Related: [Custom Asset Use Cases](https://github.com/MetaMask/Design/issues/158)

**Comment by jennypollack** [comment]
https://devpost.com/software/dc-wallet  
https://github.com/tommyz7/ethwaterloo-contract-account-metamask-plugin 
```
    "initialPermissions": {
      "confirm": {},
      "setAccountLabel": {},
      "setSelectedAddress": {},
      "wallet_manageAssets": {},
      "wallet_manageIdentities": {}
    }
```

**Comment by jennypollack** [comment]
https://devpost.com/software/connexion-vy3a9c
https://github.com/Ryan-Ouyang/metamask-messaging
```
    "initialPermissions": {
      "alert": {},
      "eth_accounts": {},
      "wallet_manageAssets": {}
    }
```

**Comment by jennypollack** [comment]
https://devpost.com/software/wallet-notify is a fork of metamask looking to get [their changes](https://github.com/MetaMask/metamask-extension/pull/7381) merged into the extension (not the plugin beta extension)

- [ ] more investigation required to determine what/if the plugin use case is here

**Comment by jennypollack** [comment]
https://devpost.com/software/carbonguilt 
https://github.com/EthWaterloo-Hackathon/carbon-guilt-snap 
```
    "initialPermissions": {
      "eth_accounts": {},
      "metamask_addToken": {},
      "metamask_getTxById": {},
      "metamask_tx:status-update": {},
      "metamask_getPluginState": {},
      "metamask_updatePluginState": {}
    }
```

**Comment by omnat** [comment]
First explorations here: https://www.figma.com/file/R2miYY21nfaIOx4sdMyCjw/Quick-explorations?node-id=1%3A2

To create project / epic of plugin UX work @omnat
