### ISSUE TITLE
Action Screens for Fishing Attacks

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#18]
User story and sketches from Mural session
https://app.mural.co/t/consensys3989/m/consensys3989/1527187224674/c1ede03935b891c510322112e456029556233e22

![b82850be-8b58-4462-8e30-c5c2e2419a2e](https://user-images.githubusercontent.com/597770/40519824-a89e5d78-5f76-11e8-8fa5-68b8cdbec03c.png)

**Comment by bdresser** [comment]
we can extend the designs in #11 to help indicate what's happening here - specifically when a user is asked to call an `approve()` function. 

perhaps with a more detailed special-case header, or with a small line of text that describes what's happening ("you're approving 0xe9d to spend up to 300 of your OMG at any time"). 

can also add a support article & "Learn more" link

**Comment by bdresser** [comment]
We've shipped a custom template for `approve` calls and are now showing known function names.

Other improvements are covered by https://github.com/MetaMask/Design/issues/38 and https://github.com/MetaMask/metamask-extension/issues/5087
