### ISSUE TITLE
Advanced Settings: Dev-specific UI Controls + Functionality 

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#2]
We're starting to see a clearer dividing line between basic and advanced(dev-specific) features. The easiest place to put on/off switches for dev-specific functionality and ui control customizations is probably inside of settings.

Advanced features would include:
- Network switcher
- TX data field 
- nonce controls
- Advanced Gas controls
- Reset Account (which only affects TX history??)
- Auto approve my transactions within an X window of time. (to reduce the amount of tx over and over)

Wireframe:
![image](https://user-images.githubusercontent.com/597770/36817343-ad42f470-1c95-11e8-99ff-757b76cd4449.png)

@danfinlay @Zanibas @kumavis Thoughts?

**Comment by danfinlay** [comment]
> Auto approve my transactions within an X window of time. (to reduce the amount of tx over and over)

That one's scary, not sure I approve of it.

The rest is good.

Related to https://github.com/MetaMask/metamask-extension/issues/3169

**Comment by cjeria** [comment]
@danfinlay Yea, i wasn't sure of that one myself. I talked to someone at the retreat who expressed being annoyed with having to repeatedly approve transactions as he was developing his dapp on test nets. Thought I'd capture here so that I don't forget about it.

**Comment by danfinlay** [comment]
I think there are other ways for developers to improve that experience, like running Ganache locally.

**Comment by cjeria** [comment]
Cool, didn't know that was possible with Ganache. Crossed that one out

![image](https://user-images.githubusercontent.com/597770/36860506-48014f98-1d36-11e8-8a10-0cf80d073430.png)

**Comment by cjeria** [comment]
I would add to the advanced settings a "display function data" switch.

We'll show function name on the top of a confirm TX screen by default for all transactions.
For example, a "Transfer" function type would look like this in the top bar:

![image](https://user-images.githubusercontent.com/597770/39269574-19ec1642-4888-11e8-8c0a-57c2a90bef70.png)


However, if advanced users chooses to see additional data associated with the function type, they can turn on this feature in settings.

### Example of what function data could look like:
```
 {
    name :'Transfer From',
    methodSignature: 'transferFrom( address, uint256 )`,
    args: [
      { type: 'address', value: '0xabcdefg1234567890 },
      { type: 'uint256', value: '235' }
    ]
  }
```

**Comment by danfinlay** [comment]
That looks like a huge improvement, I agree the parameters can probably be reserved for advanced users, and could even be captured on a separate issue.
