### ISSUE TITLE
Make network loading menu more obviously a menu

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#20]
<img width="351" alt="screen shot 2018-06-01 at 11 18 22 am" src="https://user-images.githubusercontent.com/542863/40816060-97744ce0-64ff-11e8-96d2-1c63ddb0b68c.png">

This user did not guess that the top right spinner was a menu, and I don't blame him!

How about a little carrot or something to imply the menu-ness of it? `v`?

**Comment by cjeria** [comment]
@danfinlay We just talked about on the support call yesterday! As you mentioned, the quick fix could be a carrot maybe even a timeout with a message.
