### ISSUE TITLE
Transaction History should show incoming and outgoing transactions

### ISSUE THREAD

**Issue by snreynolds** [MetaMask/Design#26]
Currently, only outgoing transactions are shown in the history but displaying incoming transactions and outgoing transactions would be a nice feature. Differentiate inbound and outbound with colors(green, red) or symbols (+, -) so users easily understand what is deducted/added to their total balance.

**Comment by bdresser** [comment]
Relates to https://github.com/MetaMask/metamask-extension/issues/133
