### ISSUE TITLE
Moving between transactions in the confirm screen

### ISSUE THREAD

**Issue by alextsg** [MetaMask/Design#30]
In the old UI, users were able to move between transactions when confirming:
![image](https://user-images.githubusercontent.com/8051479/41561561-1e1b21bc-72ff-11e8-9473-d8b41173a9e6.png)
In the new UI, we currently render the oldest transaction and the user has to confirm/reject transactions in order. Should we implement the same UX in the new UI?

**Comment by bdresser** [comment]
So right now when you prompt a transaction, you can either confirm it in the standalone popup window, or in the popup attached to the extension bar. The behavior for stacked transactions is different in each view:

* In the standalone popup window, we show the oldest transaction first (in the order they were proposed). 
* In the popup attached to the extension bar, we show the most recent transaction first.
* As @alextsg mentions above, in the Old UI you can move between the transactions using the element shown, but in the New UI you can't.

I think we should standardize in showing the transactions in the order they were proposed, which also has the security benefit of preventing dapps from proposing a new transaction at the last moment. 

We should also include the ability to move between the proposed transactions, as in the old UI. 

Could be something as simple as this, although @cjeria should take a look

<img width="200" alt="screen shot 2018-08-22 at 2 30 01 pm" src="https://user-images.githubusercontent.com/1016190/44492024-eae2f080-a617-11e8-8089-1f914fd7b4ac.png">

**Comment by cjeria** [comment]
Concept for displaying unconfirmed or "stacked" transactions.

![image](https://user-images.githubusercontent.com/597770/44868127-bd60fd00-ac3e-11e8-8d5a-4bc1c914bd91.png)

**Comment by bdresser** [comment]
~@alextsg @cjeria would allowing tx confirmation in whatever order the user wants cause nonce issues?~

~I'm actually ok with the UX as-is, especially since it keeps tx in nonce order -- I just think we should standardize behavior as described above.~

Chatted with whymarrh who informed me that nonce is set when a tx is submitted which is cool 😎 

Should probably wait until after #3425

**Comment by bdresser** [comment]
this was implemented as part of batch transactions
<img width="362" alt="Screen Shot 2019-04-02 at 11 10 28 AM" src="https://user-images.githubusercontent.com/1016190/55425768-12982080-5538-11e9-9861-08ae39abad51.png">
