### ISSUE TITLE
Trezor Support: UX/UI Fixes

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#33]
### Connect to Trezor Screen
Add more context to the "connect" to Trezor screen. 
- This screen needs more context - include icon and explainer text w/link to "learn more"
- Learn more to link to a blog post about hardware support feature.

![image](https://user-images.githubusercontent.com/597770/41788320-1d047eb4-7600-11e8-973f-c111baff4130.png)

### Trezor accounts screen
The “previous” and “next” buttons needs slight design consideration.
![image](https://user-images.githubusercontent.com/597770/41788385-5377003e-7600-11e8-8059-4769d219d637.png)

### Trezor account viewing 
- Once trezor is connect, it’s not obvious that the account is a hardware wallet account, other than "imported". Maybe add a hardware account icon/indicator somewhere.

### Account Dropdown
- Accounts should be remembered. Need to design a way to "forget/hide accounts".
- Add a "Disconnect hardware" button to unmount the HW.

### Functionality notes
- Hardware wallet accounts should appear under the account switcher dropdown
- Accounts should be remembered. Need to design a way to "forget/hide accounts".
- Hardware needs to be unlocked and connected to make transactions and sign messages

### Usability Test
Let's test this feature internally and iterate on the ux if needed

**Comment by bdresser** [comment]
trezor support is merged, closing
