### ISSUE TITLE
Send page Transaction Fee feedback

### ISSUE THREAD

**Issue by alextsg** [MetaMask/Design#37]
![image](https://user-images.githubusercontent.com/8051479/43230099-eba57464-901b-11e8-9ec2-23cb136f745c.png)

- There may not be enough room to display the prices for different currencies, so I think we're going with a design similar to:
![image](https://user-images.githubusercontent.com/8051479/43230057-c3e95b16-901b-11e8-8a92-7b6db66d6165.png)
Can we get a mockup with our UI styles?

- If the user clicks "Advanced options" to enter the speed up modal, manually enters in a new gas price, then returns back to the send screen, how do we represent the new custom value in the send screen since it wouldn’t be one of the 3 options?
- If the user enters in a new value via "Advanced options", then decides he wants to go back to one of the pre-set options, how does he do that?
- If there is an error with the API/request and we are unable to retrieve the 3 values for the options, what is the fallback? Show the current design?
![image](https://user-images.githubusercontent.com/8051479/43229996-88265ec6-901b-11e8-8297-192a525fdc88.png)

**Comment by cjeria** [comment]
Here's a slight enhancement to the gas component and the basic flow/logic.  

<img width="637" alt="image" src="https://user-images.githubusercontent.com/597770/44365906-e4217580-a47f-11e8-9173-fd9a1e3874f8.png">


> If there is an error with the API/request and we are unable to retrieve the 3 values for the options, what is the fallback? Show the current design?

Let's fall back to this component. I intentionally omitted the lever icon to be more explicit with copy "Advanced options"
<img width="647" alt="image" src="https://user-images.githubusercontent.com/597770/44179569-5bd05880-a0ac-11e8-9791-f29b9df83c93.png">

Other thoughts:
- I'm tempted to experiment with putting the gas selection in a second step in the flow gas is becoming an important step in the send flow and we'll be able to use this nicer component.
<img width="423" alt="image" src="https://user-images.githubusercontent.com/597770/44179691-25470d80-a0ad-11e8-9542-c78f5472ef6f.png">

Thoughts?

**Comment by bdresser** [comment]
@cjeria let's start with the first option to get this out with minimal changes to what Kyokan already has - then we can think about breaking this out into its own step as the next iteration

**Comment by bdresser** [comment]
Closing this as part of https://github.com/MetaMask/metamask-extension/issues/4789
