### ISSUE TITLE
Opt-in screen for analytics

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#49]
We need to show users a screen that asks for opt-in screen to  allowing MetaMask report basic usage metrics. We very much want people to enroll (rather than opt-out) so that we have data that can inform our product development. At the same time, it's important to (a) allow users to opt-out if they want to, and (b) inform users about what specific privacy protections we can promise. 

Some text we may want to include on the opt-in screen..
```
MetaMask would like to gather basic usage data to
better understand how our users interact with the extension.
This data will be used to continually improve the UX of our product.
If you care about the usability of the Ethereum ecosystem, 
please consider allowing these basic analytics

MetaMask will... 
* never collect addresses, keys, transactions, balances, or any other personal information
* never collect your IP Address
* never sell any data for profit. Ever!
* always allow you to un-enroll from these analytics via the settings menu.
* maintain a public dashboard of aggregate data for the community to learn from
```

More details to come based on conversations with Kyokan around Matomo specifics and conversation with Legal

cc @danjm @cjeria @omnat

**Comment by omna** [comment]
Could we add the following point to this @bdresser?
Metamask will..
- allow users to sign-up for user research. in this case only, their email address will be asked to reach out to participants

**Comment by bdresser** [comment]
I think it might be better to include this in a separate step - maybe a banner on the home screen, as we discussed? We want to do as much as possible NOT to scare people away from the metrics opt-in, and asking for an email address or complicating the UI with a double check box may affect the rate of people who consent. 

If we're explicitly asking for research opt-in separately, I don't think we need to include that text here.

**Comment by omnat** [comment]
Oh yes - my bad! You are right, not in the opt-in flow, but this will live in a banner/prompt and settings.

**Comment by 2-am-zzz** [comment]
Where will the email be inputted? When they opt-in?

**Comment by omnat** [comment]
Email to be inputted after a user signs-up for user research. This would be another opt-in option (NOT in the main analytics opt-in screen, but perhaps in the Settings menu?), and prompted sometimes to bring it to users' attention that this option to participate in user research exists. 

Good to make it clear to users that if they sign-up for research, their analytics data will be associated with their email addresses - which is used for R&D purpose only (this identifiable data is stored in Matomo, viewable by MetaMask team - but not made identifiable to public)

**Comment by 2-am-zzz** [comment]
Cool--hopefully it passes through GDPR compliance.

**Comment by bdresser** [comment]
Sounds good - agree this secondary "contact me for research" opt-in should be very explicit. And (per slack) will probably be a second step after metrics MVP is live.

**Comment by bdresser** [comment]
language per our legal team

"MetaMask would like to gather basic usage data to better understand how our users interact with the extension. This data will be used to continually improve the UX of our product. If you care about the usability of the Ethereum ecosystem, please consider allowing these basic analytics. This data is aggregated and is therefore anonymous for the purposes of General Data Protection Regulation (EU) 2016/679.

For more information in relation to our privacy practices, please see our Privacy Policy here [link to Privacy Policy]

MetaMask ...
* does not collect Ethereum wallet addresses, keys, transactions or balances
* will never sell any data for profit. Ever!
* always allows you to un-enroll from these analytics via the settings menu [link to Settings menu].
* maintains a public dashboard of aggregate data for the community to learn from

[I Accept] button"

**Comment by danfinlay** [comment]
That language is _very_ verbose, I think you could probably hide most of it behind a "Learn more" link.

How about just:

> MetaMask would like to gather basic usage data to better understand how our users interact with the extension. This data will be used to continually improve the UX of our product.

**Comment by bdresser** [comment]
sounds good to me @danfinlay 

we do need to include the GDPR line at the legal team's request.

How bout 

> MetaMask would like to gather basic usage data to better understand how our users interact with the extension. This data will be used to continually improve the UX of our product. This data is anonymous by GDPR standards.


Could even have that last sentence in a light gray or something.

**Comment by bahnju** [comment]
![option_1](https://user-images.githubusercontent.com/32208835/51589795-448c6700-1ea5-11e9-8c5f-48d08486ef8f.png)

Above is what I think is a good option for this but definitely can change. Process and notes here: https://docs.google.com/document/d/11gBjDnn0WBI73zHj0tq8P5vu3aTpf7qb_0TdIweThVw/edit?usp=sharing

**Comment by bdresser** [comment]
thanks @bahnju! good stuff. 

- we've spoken with the legal team in the past about making the terms / privacy policy step smoother, but they insist that a scroll-to-bottom approval is the most legally defensible. they're being really cautious about this. I'd love to improve that screen at some point (it's not super obvious you need to scroll down) but that is a project for another day. for now, we should leave the "agree to terms" on a second page.

- the overall theme of metrics is that we should be really honest and transparent. I think it's much more direct to give users a yes/no option rather than a pre-checked box with small text, which many might see as a coercive dark pattern. let's be clear & direct about it: are you okay with us tracking some anonymous data? Our community and reputation are more important than a high opt-in rate for tracking. 

- might also be nice to include some of those specifics mentioned in this comment, since I assume many users will have questions about what specifically we are tracking. This will add up to a lot of text, so it could be nice to include some friendly visuals.

- some context that we've talked about live but isn't on this issue: this screen will be shown to (a) new users during onboarding, and (b) existing users the first time they open the extension after this goes live.

**Comment by omnat** [comment]
Thanks @bahnju! Left comments on Figma prototype. 

Largely echoing Bobby's feedback on _asking_ people for consent instead of a pre-filled checkbox: while this adds 1 more step while users interact with the app, it also adds a sense of control. Sharing intentionally is more important experience we want here for reasons mentioned by Bobby.

+1 on inviting visuals to complement copy
