### ISSUE TITLE
Allow switching value denomination on send

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#51]
I know we have system wide default for showing fiat or crypto when showing values, but for sending, everyone needs the ability to switch it spontaneously. Sometimes I want to send 1 eth, sometimes I want to send 10 dollars of eth.

Jaxx has a great switcher for this on their wallet for inspiration.

Not finding this setting can be frustrating for users: https://www.reddit.com/r/Metamask/comments/af6z13/metamask_getting_worse/?st=JQTPK83D&sh=045c72d3

**Comment by lyricalpolymath** [comment]
+1 this was a frustrating interaction
you could make the second smaller denomination clickable
and when you click it, it becomes the main input field
it switches with the current main option
