### ISSUE TITLE
Address Book - Send flow

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#53]
Design: https://www.figma.com/proto/giaffk6qfl9eMMjoPFjJkGnt/Contact-List?node-id=0%3A1&viewport=366%2C92%2C0.11397&scaling=min-zoom

Dev issue: https://github.com/MetaMask/metamask-extension/issues/6365

**Comment by cjeria** [comment]
Made updates the send flow in the prototype linked above. Feedback welcomed!

**Comment by cjeria** [comment]
Quick 3min video explainer of an optimized flow that reduces the number of clicks introduced from the previous iterations. The prototype link remains the same. cc @omnat @bdresser @danjm @jennypollack @frankiebee 
https://www.dropbox.com/s/cwmlvp2z5ls0hl1/send%20flow%20with%20address%20book%20-%20optimized.mov?dl=0

**Comment by bdresser** [comment]
love this @cjeria! just as functional, but feels way smoother & more in keeping with our current design. good stuff 👍

**Comment by omnat** [comment]
Great! I like this a lot Christian! Addressed all those concerns in an elegant way!
