### ISSUE TITLE
Tabs & in-browser navigation

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#56]
@omnat to give research, inspiration as starting points
@cjeria to jam with Bruno on this

**Comment by bdresser** [comment]
from Bruno: 

https://cdn-images-1.medium.com/max/400/1*U3ZooChvMWkQoYmdcnBs0A.gif

**Comment by bdresser** [comment]
relates to https://github.com/MetaMask/MetaMask/issues/417

**Comment by bdresser** [comment]
http://recordit.co/PKcKSNUx2L

@omnat may have some other brower-like insights to share
* many people looking to the *top* bar for browser controls? 
* maybe worth re-visiting / re-testing after tabs exist? (user testing with real prototype or something?)

default tab behavior may influence need for a "home" button on the bottom nav bar. aka -- if new dapps are opened in new tabs, it's easier to return home. 
* should home tab be persistent? (maybe a different visual treatment?)

**Comment by omnat** [comment]
Strong insights from private beta feedback (surveys and interviews):

Browser navigation needs improvement:

- Users expect a more accessible way to get to ‘Home’. 
- Users tend to tap URL to change URL/search, but it opens up network switcher. This is frustrating, unexpected.
Network switcher should be a level lower in navigation heirarchy as per frequency of use.

**Comment by bdresser** [comment]
bruno will merge the WIP tabs branch by end of week and we can QA / iterate on the live version

some learnings
* tab thumbnail is a screenshot of the website - works fine on iOS, not so good on Android. Maybe use the favicon (on Android) instead?
* some lil bugs bruno is workin' on

**Comment by cjeria** [comment]
One aspect of the tabs view that could use improvement is the legibility of the website/dapp. Screenshots aren't always visible/clear, so I suggest we make the website favicon + URL visually larger. Here's are a couple of designs that utilize the design system colors. The right screen is an iteration that emphasizes the website name and favicon better. Feedback welcome. @brunobar79 @omnat @bdresser 

![image](https://user-images.githubusercontent.com/597770/57704591-d91efe80-7627-11e9-9cc7-2304153cb511.png)

**Comment by bdresser** [comment]
~both look good, want to make sure they hold up well when there are lots of tabs open – how do either behave when there's overflow?~ --> vertical scroll

- this is a universal set of tabs, so cool to represent which account is using which tab
- if you close all, only the blank "add tab" is left which takes user to the homepage
- from @brunobar79 - "close all" and "done" should probably not be bold, in keeping with other iOS patterns
 - could optionally add filters at some point - filter by network or by account
- maybe room for an animation if @cjeria wants

**Comment by omnat** [comment]
Design QA comments below:

<img src="https://user-images.githubusercontent.com/44038140/58140154-e5402880-7bf2-11e9-9d8a-3c03babf8f2f.jpg" width="200" height="400">

- (Android) feels like not enough tap space on the three top right options. @cjeria could you please advise on spacing?
- the 3 dots 'more options' button is disabled on a dapp homepage and gets activated on a dapp page. this is odd behavior and apparently not a problem in iOS

<img src="https://user-images.githubusercontent.com/44038140/58140155-e5402880-7bf2-11e9-8c7a-dbd489773706.jpg" width="200" height="400">

- More options recommendation per Chrome inspiration and what could make sense for smoother navigation: 'New tab', 'Add to Favorites', 'Open in browser', 'Change network'
  -- Reload by pulling down gesture, Go back using Android phone back button (different nav bar on iOS with arrows).
  -- Change network is more secondary feature than Change URL. So on tapping URL/network: allow editing/typing/copying URL and keep current network as just an indication.

**Comment by bdresser** [comment]
> the 3 dots 'more options' button is disabled on a dapp homepage and gets activated on a dapp page. this is odd behavior and apparently not a problem in iOS

none of these options are relevant on dapp pages
* could disable,
* but maybe we just dynamically change the options to show what's relevant (like network switching #88) @cjeria to choose an icon!
* tapping the URL lets the user edit the URL

**Comment by bdresser** [comment]
some notes for design QA
- can't do opacity on the tab bar on Android - it's a plain grey (from the design system palette)
- fix tap area
- animations? low priority >> pushed to V1
- "looks chunky" - may want to update proportions
- update the "more" `...` on Android (to match iOS)

**Comment by cjeria** [comment]
Figma prototype for specs:
https://www.figma.com/file/ZjvqFYvSwB90oC81N0PMHjE1/Mobile-Browser?node-id=0%3A1

**Comment by cjeria** [comment]
![image](https://user-images.githubusercontent.com/597770/58995634-3256f980-87b2-11e9-970f-3f4e376ee60a.png)
