### ISSUE TITLE
Opt-in screen for metrics

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#59]
For mobile metrics, add opt-in screen in mobile app onboarding.
This could be similarly done as in extension, while keeping best practices for mobile (especially iOS) in mind

**Comment by bdresser** [comment]
Per this [flow diagram](https://www.figma.com/file/SS6j137wIvqXYiyltHJ7rspz/Mobile-Onboarding?node-id=0%3A1), metrics opt-in should be the last step in every flow (just before user lands on the wizard)

**Comment by estebanmino** [comment]
@cjeria any update on this?

**Comment by cjeria** [comment]
@estebanmino yep! Here's a link to the design file 

https://www.figma.com/proto/SO5vb4lF4aVG04LNTOjmsABC/Opt-in-screen-for-metrics?node-id=0%3A1&viewport=61%2C-103%2C0.833973&scaling=min-zoom

Notes:
- make the message scrollable
- fix the buttons to the bottom of the page

See screenshot
![image](https://user-images.githubusercontent.com/597770/56916933-c6c99000-6a7f-11e9-9cf3-f76611bac8d3.png)

**Comment by bdresser** [comment]
as we did in the extension, can we cut that last line of copy? 
`If you care about the usability of the Ethereum ecosystem, please consider...`

Privacy Policy link goes [here](https://metamask.io/privacy.html)

Also, specific promises about what we track are subject to change once we pick a metrics system, but let's leave them like this for now

**Comment by estebanmino** [comment]
@cjeria I get a 404 with that figma link, could you please give me the correct link? thanks!

**Comment by omnat** [comment]
@estebanmino invited you, it should work now
