### ISSUE TITLE
Fox animation

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#65]
Requirements for dev on:
Where & when in the flow
How long

**Comment by cjeria** [comment]
Gif preview of the video sequence and here's an MP4 of the same video https://www.dropbox.com/s/noe0r2o9225ddyr/mobile%20splash%20screen%20animation.mp4?dl=0

![Screen Recording 2019-04-03 at 05 58 PM](https://user-images.githubusercontent.com/597770/55512873-9e927100-563a-11e9-844a-79faf2346b24.gif)

**Comment by omnat** [comment]
Note: if loading is taking longer, loop it for 1 or 2 times more and end similar way as shown in gif above.

Three places to use this same pattern:
- launching app (like shown in gif)
- loading during the ‘creating your wallet..’ screen
- in the browser when a url is loading
