### ISSUE TITLE
Sync with extension option more discoverable

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#73]
Insights and **design needs** from private beta feedback:

- people tend to go to 'Start exploring' even when they have a MM wallet they could sync. 
**Sync feature should be made more discoverable and expectation set on its easy and fast**
- after creating a new wallet and being in the app, when they want to sync/import their wallet, it seems like its not possible or they get confused by 'Import account'
**Make it possible to start the Import wallet flow from within the app** (without needing to logout)
**Make 'Import account' and 'Import wallet' more distinct** to indicate they have different function & consequences

**Comment by bdresser** [comment]
probs for sprint 14

**Comment by omnat** [comment]
Updating this to:

- Sync feature should be made more discoverable and expectation set on its easy and fast (not tucked behind Import wallet)
- In the option of: Import account.. Explain better this is importing account and what that means. also something like "Looking to import a wallet? Logout for that optiont"

**Comment by omnat** [comment]
From design sync:

For mobile public beta - for (existing) Metamask extension users, make it very clear after Metamask mobile installation that they can **very easily** sync with their extension wallet. Right now, its buried after the `Import wallet with seedphrase option`. 

Let's make `Import wallet with seedphrase `a tertiary option. So, something like:

1. User installs MM mobile and sees option to `Get Started` or `Sync wallet` 
2. User selects `Sync wallet` and then see how they can do that with Metamask extension. Same screen, lower heirarchy option is 'Have a wallet, but not with Metamask? Import with seedphrase'


Could be achieved by just changing the first screen's secondary button from `Import a wallet` to `Sync wallet` in this mock https://www.figma.com/file/SS6j137wIvqXYiyltHJ7rspz/Mobile-Onboarding?node-id=0%3A1

**Comment by bdresser** [comment]
@cjeria @omnat let's try to have this design change locked down by end of week so we can get it in mobile & still have time to submit builds!

**Comment by bdresser** [comment]
@omnat how about 

on step 1
`Start Exploring` or `Sync your Wallet`

on step 2
`Sync with Extension` or `Import using Seed Phrase`

**Comment by omnat** [comment]
Sounds good @bdresser! Extremely hacky (with screenshots, and terrible font-sizes, text update hack)  mock to convey copy update suggestions. Please ignore font sizes, spacing, button placements etc.

Step 1: Label change for button
Step 2: Give context on syncing with extension (is fast), update copy 'Settings > Advanced"

<img width="473" alt="Screen Shot 2019-07-10 at 11 25 58 AM" src="https://user-images.githubusercontent.com/44038140/60994736-ec87d680-a305-11e9-8bed-d3e82519c84b.png">

cc @cjeria this is the hacky file if you wanna  make updates https://www.figma.com/file/Gvc9H6bn5QJIFPIKw2mAqh/Mobile-Onboarding-(Copy)

**Comment by cjeria** [comment]
Designs spec for this update here -> https://www.figma.com/file/Gvc9H6bn5QJIFPIKw2mAqh/Mobile-Onboarding-Copy?node-id=69%3A199

Made an enhancement to the bg using our more colorful graphic which adds a bit more pop, although we might make updates after we get the new illustrations. Thoughts?

![image](https://user-images.githubusercontent.com/597770/61059651-f7eb0880-a3be-11e9-908e-7b5657a51521.png)

**Comment by bdresser** [comment]
latest designs per slack

<img width="489" alt="Screen Shot 2019-07-11 at 1 45 59 PM" src="https://user-images.githubusercontent.com/1016190/61084164-3f36c080-a3e2-11e9-9829-2fb0f54bbc3e.png">
