### ISSUE TITLE
Update UX for sweeping account

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#75]
In the Send flow, the "max" option could be a toggle state, where if it's enabled it will dynamically update the send amount as the user changes gas. This will help prevent users from having a small amount of ETH left over when they try to empty an account

dev work nearly complete here: https://github.com/MetaMask/metamask-extension/pull/6488

**Comment by cjeria** [comment]
New designs for the max toggle button:

Link to Figma: https://www.figma.com/proto/Ko47bJeCdyCKsePa2ObWGjln/Send-Screen?node-id=1%3A367&viewport=461%2C169%2C0.651491&scaling=min-zoom

<a href="https://cl.ly/8dff77178a86" target="_blank"><img src="https://d2aztkdj0ezvrk.cloudfront.net/items/290c0v1E0r1X131G2x2y/Screen%20Recording%202019-05-07%20at%2005.01%20PM.gif" style="display: block;height: auto;width: 100%;"/></a>

**Comment by bdresser** [comment]
LGTM @cjeria ! Cross-posting to the open PR
