### ISSUE TITLE
Create custom error pages for the browser

### ISSUE THREAD

**Issue by brunobar79** [MetaMask/Design#76]
I've added some placeholder functions that will allow us to set state in the browser and show a custom error page.

We will need design for those (404, Timeout, Unknown error)
CC: @bdresser @cjeria

**Comment by bdresser** [comment]
accelerometer fun? tilty fox?

**Comment by bitpshr** [comment]
Removing myself from this until we have designs for these pages. @cjeria, any update on this by chance?

**Comment by omnat** [comment]
Similar issue for offline behavior in #102 
And we noticed that the fox 3D head has been implemented already, so its good for now.
