### ISSUE TITLE
Onboarding forwarder

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#78]
## Problem

Today when a Dapp wants to onboard a user, they have to direct the user to install MetaMask, and then the user has to find their way back to the dapp.

## The idea

We can provide a special site that Dapps can link to for onboarding new users, which is able to automatically redirect the user to the site that sent them after the user gets their account set up!

## The Implementation

Our intern Sneh has already gotten [basic pieces merged into `develop`](https://github.com/MetaMask/metamask-extension/pull/6272) that will do this.

The catch is it requires a tab in the background that keeps reloading. It will be very briefly seen by users while redirecting to their extension store, and it's possible that users will click on it.

You can [see how it works here](http://recordit.co/b6igZIh4lQ).

Those users will need to be told something like

> You will be redirected to your Application once you complete your MetaMask account setup.

We could even link users to resume setup (where it either opens the extension install page again, or if they have MetaMask installed but haven't finished setting up, we could potentially open the full screen setup interface right there).

Anyways, you can see the minimal interface here:
http://fwd.metamask.io/

And it can be easily updated by pushing to this repo:
https://github.com/MetaMask/forwarder

http://recordit.co/b6igZIh4lQ

**Comment by bdresser** [comment]
Since we have to open the fwd.metamask.io page anyways, it could make sense to intentionally show it for a brief moment with some helpful instructions. like:

```
Welcome to MetaMask! 
In a few moments, you'll be directed to the <Browser> Store to download the MetaMask extension
This will get you set up with a wallet and allow you to start using dapps etc. 
After you're done setting up MetaMask, we'll send you back to <Origin Site> 

[ Let's go! ]
```

So we let the user read it to prime them about what is happening. Include some cute graphics. Maybe automatically send them along to the chrome store after 10-15 seconds or so. 

Otherwise it seems a little buggy/spammy and folks may close the additional tab

**Comment by omnat** [comment]
Prototype here for dev-handoff (1st flow: redirect to chrome store, and redirect back to dapp site after user done with incremental security): https://www.figma.com/proto/HEgBtmMHUQSlyQTyyeKSvD4R/Onboarding-Flow?node-id=436%3A383&viewport=3083%2C608%2C0.41909533739089966&scaling=min-zoom

@danjm

**Comment by bdresser** [comment]
Looks good! Couple questions:
* what happens at the end of the flow? 
  * Do we just close the MetaMask tab, which would drop the user on the last tab they had open (probably the Chrome store)? 
  * Or do we redirect the MM tab to the dapp that the user started on? (They might then have two of that tab open.) 
  * Or, is it possible to send the user to an already-opened tab? @danjm @omnat 
* Just want to note that we can't immediately prompt the "connect" action - that will happen when the dapp wants it to.

**Comment by danfinlay** [comment]
> what happens at the end of the flow? 

I definitely think "Redirect to the dapp the user started on" is the right choice. We will need to also reload that tab, since otherwise it will have no connection to the freshly-installed MetaMask. (Opening a new tab to that site may be required).

**Comment by danfinlay** [comment]
> Just want to note that we can't immediately prompt the "connect" action - that will happen when the dapp wants it to.

We *could* bake a connect request into the referral link format, so that MetaMask actually *does* show the connect request before linking back to the site & reloading it. Just pointing out that is technically feasible.

**Comment by bdresser** [comment]
> We could bake a connect request into the referral link format, so that MetaMask actually does show the connect request before linking back to the site & reloading it.

Cool! Does this need to be spec'd or is it trivial to add?

**Comment by danfinlay** [comment]
I think any spec could be part of implementation. For example, just formatting the connect request into a URL query parameter. Would push the question back to design, like "When in the setup flow should the connect screen appear?"

**Comment by omnat** [comment]
> what happens at the end of the flow?

What would make sense is dropping the user back to the context where Metamask was introduced. 

In the prototype, this means the flow ends back at dapp site where the user first wanted to connect with a wallet. On clicking 'Connect to Metamask', if the user had a wallet, the connect request would pop-up. In this flow, user doesn't have Metamask yet, so we guide them to get Metamask; i.e., we redirect them to chrome store and then to setup Metamask. 

So after user does the setup, user is brought back to the initial action they intended to do, which is Connecting with Metamask.

From Dan's comment, it looks like this is technically possible.

**Comment by bdresser** [comment]
> In the prototype, this means the flow ends back at dapp site where the user first wanted to connect with a wallet.

Totally agree @omnat! 

Just want to understand whether that means
(1) opening a new tab with that origin site (for a grand total of four tabs 😅)
 or 
(2) closing the MM and Chrome Store tab and bringing user back to original page (maybe not technically possible, do you know @danjm or @danfinlay?)

Either way, good call to include the Connect request so it's super seamless 👍

**Comment by danfinlay** [comment]
> (2) closing the MM and Chrome Store tab and bringing user back to original page (maybe not technically possible, do you know [removed-to-not-ping]?)

Pretty sure this _is_ technically possible, but if we do return them to the page, we need to reload that page to trigger detection of MetaMask.
