### ISSUE TITLE
Incremental account security on extension

### ISSUE THREAD

**Issue by bdresser** [MetaMask/Design#79]
We should adapt the mobile "incremental security" flow for the extension

To start, may make sense to leave onboarding as-is (ask the user to backup their seed) but just include a "skip" option, which would trigger the account security flow later (when the user has value)

Dev issue https://github.com/MetaMask/metamask-extension/issues/5849

Figma [here](https://www.figma.com/file/5c9pypHsGvPFIWaKr1vmg2/Mobile-Public-Beta---update-after-testing)

**Comment by bdresser** [comment]
from Dan in design sync: "make the button scary!"

from Christian: maybe have a persistent banner that tells the user their account isn't secure.

**Comment by omnat** [comment]
from design sync:
- Omna to setup a Mural jam call to put it all together per differences from mobile and how we adapt mobile designs to desktop/extension

**Comment by omnat** [comment]
Notes from conversation
- Keep current onboarding flow, allow skipping
- Persistent trigger to backup after value above a certain level (3 tier increments)
- Make the 'download seed backup file' option clearer (a button?)

- Create password step -- add copy from mobile explaining why its needed
- Before uninstalling -- reminder to user to back-up seedphrase if they want to recover this wallet later https://github.com/MetaMask/metamask-extension/issues/6601

https://www.figma.com/file/HEgBtmMHUQSlyQTyyeKSvD4R/Onboarding-Flow?node-id=0%3A1

**Comment by omnat** [comment]
Note from design call:

- How do we define 'low' 'high' value?
- If user Skips, add a warning to let them know this could lead to loss of account (and value in it.
Alternative to extra screen would be a 1-liner next to ‘Skip’ button (“Skipping this step could make you lose your account and value”)

**Comment by omnat** [comment]
@cjeria Made a pass at this and added Onboarding forwarder from #78 part of this flow as well. Sent you Figma link in Slack (in case you miss my message there)

**Comment by omnat** [comment]
First pass at this

- I tried to update copy per our latest mobile prototype as well as it was tested.
- Made a suggestion on ‘Create / Import’ account step (following the common Sign-up & Login pattern on sites).
- Per Onboarding research outcomes, also made a suggestion to add intro slides on extension (this is for future - when we have illustrations. But could follow from mobile intro slides).
- Added Onboarding forwarder (#78) from issue as part of flow as well, but didn’t think about it much.  

Figma file: https://www.figma.com/proto/HEgBtmMHUQSlyQTyyeKSvD4R/Onboarding-Flow?node-id=436%3A0&viewport=1216%2C456%2C0.13239742815494537&scaling=min-zoom

@cjeria added during review of design: Screen for onboarding forwarder added to Figma. As indication for user when onboarding on what to expect (how long setup takes, why install needed)

This is open for feedback @bdresser @cjeria

**Comment by bdresser** [comment]
@omnat on a roll w these mock ups!!! 
* I like the more prominent `Download` link -- if I download, can I still skip, or does that button disappear?
* Did "Secret Recovery Code" test better than "Seed Phrase" or "Recovery Code" or "Backup Phrase" or any of the other stuff we could use? It feels a little super-spy to me but I'm cool with whatever resonates best with users. 
* We'll need a version of the "Done / Welcome" screen after the user has skipped backup that *doesn't* mention the redirect. Like
> Welcome to MetaMask! You're ready to connect with dapps, buy ETH and tokens, and explore the decntralized web.
Since you didn't back up your Recovery Phrase, you won't be able to recover your account if you're locked out. We'll remind you periodically, but make sure to back up before you store value in your wallet!

..or something. Eventually could lead to onboarding wizard or dapp homepage (!) after completing onboarding :)

**Comment by omnat** [comment]
High-fidelity prototype and dev-handoff is next.

**Comment by omnat** [comment]
Final prototype here for dev-handoff: https://www.figma.com/proto/HEgBtmMHUQSlyQTyyeKSvD4R/Onboarding-Flow?node-id=436%3A383&viewport=3083%2C608%2C0.41909533739089966&scaling=min-zoom

@danjm
