### ISSUE TITLE
Create transaction "outbox" with "next up" at the top

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#8]
We regularly have users who get confused by the order of transaction processing. They'll have one transaction stuck, and so they'll keep trying to send more transactions to fix the issue, even though they're all stuck behind that first one.

I had this idea for separating the tx list into "sent" and "outbox", where the outbox would have the "up next" somehow visually highlighted at the top (exaggerated in the example I made here).

We would also only show the `retry with higher gas` button on that next transaction, since it's the one that is holding the rest of them up.

![pure simple](https://user-images.githubusercontent.com/542863/37177710-147150e8-22d5-11e8-8272-37a0c76e4cca.png)
![annotated](https://user-images.githubusercontent.com/542863/37177718-17cf6ca2-22d5-11e8-9f21-84769ce0edae.png)

Here you can see:
1. The highlighted "next up" section, to bring focus on the next tx.
2. Separating the pending txs from completed txs.
3. The other tx tabs (what other sections might make sense?)
4. Reversing tx order, so the next up is at the top, to imply the order of processing.

Related issues:

Only showing the retry/cancel buttons on next up:
https://github.com/MetaMask/metamask-extension/issues/2693
https://github.com/MetaMask/metamask-extension/issues/2691

**Comment by bdresser** [comment]
closing in favor of #25
