### ISSUE TITLE
Payment Request: Receiver Flow

### ISSUE THREAD

**Issue by cjeria** [MetaMask/Design#83]
Design jam whiteboard. Related to #57 

https://app.mural.co/t/consensys3989/m/consensys3989/1555436990752/2decd93e46c813e6414dedeba87f70417cbcfb38

**Comment by cjeria** [comment]
Added the receiver flow in the request flow prototype:
https://www.figma.com/proto/akfSHj495hySaUEvXeQH0NNp/Payment-Request?node-id=308%3A112&viewport=485%2C163%2C0.22483618557453156&scaling=scale-down

**Comment by cjeria** [comment]
Design QA on mobile MVP version:

- Asset search bar in android not showing (omna to verify)
- request amount screen should prompt the keyboard right away
-- button on this screen should be above the keyboard
-- when swapping primary currency, it shouldn't clear the value

**Comment by omnat** [comment]
Open questions from design sync:
- How does link work when receiver wants to send from extension? Or do we just keep mobile first for beta? Can we trigger a confirm screen with address, value pre-populated?  
- If receiver has multiple wallets and Metamask, can the link open in Metamask by default?
- If receiver has Trust, Coinbase and not Metamask, what happens? Shall we send them to Metamask install page (same as when receiver doesn't have Metamask installed)

**Comment by bdresser** [comment]
- we need a separate issue for the extension to handle these universal links
- if we use `ethereum:` address forwarding, it will open any wallet. If we use a `app.metamask` link it will just open MM or open app store if no MM installed - has downstream effects on ecosystem friendliness
  - let's go with pushing users to MM for now and can update based on community response (it's easy to update)

**Comment by cjeria** [comment]
Example request link: https://metamask.app.link/send/0x854281CA900c4a94386B68d51e0067e4944D9746@4?value=5e17

Expected behavior on desktop is for link to trigger a metamask prefilled pop-up confirm screen

**Comment by omnat** [comment]
Ready to build @danjm 
Will need design QA after implementation in extension.
