### ISSUE TITLE
Show reverse-resolved ENS names when they are detected

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/Design#89]
Anywhere we show an address (`0x1234567890abcdef`), we _may_ be able to show an ENS name instead (`danfinlay.eth`), and when we can, we should!

Related to MetaMask/metamask-extension#5294

**Comment by bdresser** [comment]
chatting with @danfinlay 

tentative hierarchy when displaying should be
nickname > ens name > address

might need a card to display adddress details

**Comment by bdresser** [comment]
<img width="561" alt="Screen Shot 2019-06-27 at 2 03 15 PM" src="https://user-images.githubusercontent.com/1016190/60300681-5a82d580-98e4-11e9-8fe1-120cbd91dc9f.png">

**Comment by whymarrh** [comment]
This functionality was added to the extension via MetaMask/metamask-extension#7177
