### ISSUE TITLE
Payment channels (Experimental feature)

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#93]
Related to : #85

**Comment by bdresser** [comment]
<img width="1375" alt="Screen Shot 2019-06-05 at 11 01 05 AM" src="https://user-images.githubusercontent.com/1016190/58978714-3f0f2980-8781-11e9-8ff9-3ffe6f97e5df.png">

https://www.figma.com/file/K1a0m5VRohRZV6EcpNzL6qxr/Payment-Channels?node-id=0%3A1

https://docs.google.com/document/d/1NReZQ29WWcxbwpGygWmT0jFudI7CuU6u13S07oBW7Go/edit#

**Comment by bdresser** [comment]
closing in favor of https://github.com/MetaMask/Design/issues/86
