### ISSUE TITLE
Design QA 

### ISSUE THREAD

**Issue by omnat** [MetaMask/Design#95]
Design QA on builds

**Comment by omnat** [comment]
[
![Screenshot_20190529-102222](https://user-images.githubusercontent.com/44038140/58577673-d281b100-81fb-11e9-8dac-89f8f1e08264.jpg)
](url)

Spacing check for top right buttons

**Comment by chikeichan** [comment]
- [ ] https://github.com/MetaMask/metamask-extension/issues/6510 (need definition)
- [ ] https://github.com/MetaMask/metamask-extension/pull/6650 (need review)
- [ ] https://github.com/MetaMask/metamask-extension/pull/6648 (need review)

**Comment by omnat** [comment]
From Christian:
Synced on above issues with Jacky. Handover done. Open for final QA after implementation.
